### ISSUE TITLE
how can i complie it?

### ISSUE THREAD

**Issue by Fuatnow** [leaf3d/leaf3d#2]
error:

By not providing "FindGLFW.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GLFW", but
  CMake did not find one.

  Could not find a package configuration file provided by "GLFW" with any of
  the following names:

```
GLFWConfig.cmake
glfw-config.cmake
```

  Add the installation prefix of "GLFW" to CMAKE_PREFIX_PATH or set
  "GLFW_DIR" to a directory containing one of the above files.  If "GLFW"
  provides a separate development package or SDK, be sure it has been
  installed.

There only some cmakelists.txt files. My system is windows, i don't know GLFW need put where.

**Comment by zuck** [comment]
First of all you need to install dependencies on your system.

* For GLFW: http://www.glfw.org/docs/latest/compile_guide.html
* For Assimp: http://assimp.sourceforge.net/lib_html/install.html

Then use **CMake** to build the project:

```
mkdir Build && cd Build && cmake ..
```
