### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [leaf3d/leaf3d#4]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “l3dTerminate”](https://github.com/leaf3d/leaf3d/blob/c3eb0661a05b448bb02a7a62dbf0a50f339ca3e4/Engine/leaf3d.cpp#L90 "Update candidate").

**Comment by zuck** [comment]
Fixed with ab82e8c

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/leaf3d/leaf3d/commit/ab82e8c0d21d92840dc459f9ed00920494b945a4#diff-046ebf7a12eab7f1d99b67a994986425fe65f313e3279dd30d55529653b1313eL90 "Remove unnecessary null pointer check").
