### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [leaf3d/leaf3d#5]
I would like to point out that identifiers like “[`_l3dMeshSortFunctor`](https://github.com/leaf3d/leaf3d/blob/ab82e8c0d21d92840dc459f9ed00920494b945a4/Engine/L3DRenderer.cpp#L41 "Update candidate")” and “[`_renderer`](https://github.com/leaf3d/leaf3d/blob/ab82e8c0d21d92840dc459f9ed00920494b945a4/Engine/leaf3d.cpp#L38 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by zuck** [comment]
Fixed with 4f070e0 and 2eabcc7.

**Comment by elfring** [comment]
Thanks for your source code adjustments.
